version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/srtider_kart
    networks:
      - strider_network

networks:
  strider_network:
    external: true
